// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mocks/example.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	example "gl.eda1.ru/go/go-service-template/internal/domain/example"
	gomock "go.uber.org/mock/gomock"
)

// MockExampleRepository is a mock of ExampleRepository interface.
type MockExampleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExampleRepositoryMockRecorder
}

// MockExampleRepositoryMockRecorder is the mock recorder for MockExampleRepository.
type MockExampleRepositoryMockRecorder struct {
	mock *MockExampleRepository
}

// NewMockExampleRepository creates a new mock instance.
func NewMockExampleRepository(ctrl *gomock.Controller) *MockExampleRepository {
	mock := &MockExampleRepository{ctrl: ctrl}
	mock.recorder = &MockExampleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExampleRepository) EXPECT() *MockExampleRepositoryMockRecorder {
	return m.recorder
}

// FindCounter mocks base method.
func (m *MockExampleRepository) FindCounter(ctx context.Context, id int64) (*example.ExampleCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCounter", ctx, id)
	ret0, _ := ret[0].(*example.ExampleCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCounter indicates an expected call of FindCounter.
func (mr *MockExampleRepositoryMockRecorder) FindCounter(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCounter", reflect.TypeOf((*MockExampleRepository)(nil).FindCounter), ctx, id)
}

// InsertCounter mocks base method.
func (m *MockExampleRepository) InsertCounter(ctx context.Context, counter *example.ExampleCounter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCounter", ctx, counter)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCounter indicates an expected call of InsertCounter.
func (mr *MockExampleRepositoryMockRecorder) InsertCounter(ctx, counter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCounter", reflect.TypeOf((*MockExampleRepository)(nil).InsertCounter), ctx, counter)
}

// UpdateCounter mocks base method.
func (m *MockExampleRepository) UpdateCounter(ctx context.Context, counter *example.ExampleCounter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", ctx, counter)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockExampleRepositoryMockRecorder) UpdateCounter(ctx, counter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockExampleRepository)(nil).UpdateCounter), ctx, counter)
}
