services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql1
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Yekaterinburg
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=accounting_eda1
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_RANDOM_ROOT_PASSWORD=false
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.10.1-management-alpine
    container_name: rabbit1
    hostname: rabbitmq
    volumes:
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-service
    image: go-service:latest
    env_file: ".env"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
    restart: unless-stopped

volumes:
  mysql-data: