// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=./mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "gl.eda1.ru/go/go-service-template/internal/controller/http/v1/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockExample is a mock of Example interface.
type MockExample struct {
	ctrl     *gomock.Controller
	recorder *MockExampleMockRecorder
}

// MockExampleMockRecorder is the mock recorder for MockExample.
type MockExampleMockRecorder struct {
	mock *MockExample
}

// NewMockExample creates a new mock instance.
func NewMockExample(ctrl *gomock.Controller) *MockExample {
	mock := &MockExample{ctrl: ctrl}
	mock.recorder = &MockExampleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExample) EXPECT() *MockExampleMockRecorder {
	return m.recorder
}

// PlusValue mocks base method.
func (m *MockExample) PlusValue(ctx context.Context, id int64, request *dto.ExampleRequest) (*dto.ExampleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlusValue", ctx, id, request)
	ret0, _ := ret[0].(*dto.ExampleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlusValue indicates an expected call of PlusValue.
func (mr *MockExampleMockRecorder) PlusValue(ctx, id, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlusValue", reflect.TypeOf((*MockExample)(nil).PlusValue), ctx, id, request)
}
