app:
  name: 'go-service'
  version: '0.0.1'

http:
  port: '8083'

grpc:
  port: 9080
  enable_server_reflection: true

logger:
  log_level: 'debug'
  log_out: 'json'

mysql:
  timeout: '3s'

rabbitmq:
  rmq_exchange_name: 'go-service'
  rmq_exchange_type: 'direct'
  rmq_queues:
    go-service: 'go-service'